<!DOCTYPE html>
<html>
<?php include('headerdito.php') ?>
<div class="privacyMaster">

    <div class="subContPrivacy">

        <div class="privacyLeft">
            <h1>Privacy Policy</h1>
            <p class="headPrivacyP">This Privacy Policy will help you better understand how we collect, use, and share your personal information.</p>
            <p>Datagen Facilities, OPC is the sole owner of the information collected from these companies.</p>
            <p>Our Privacy Notices, Terms, and Conditions are displayed clearly and visibly in our websites in keeping with our company’s policies on transparency and full disclosure. This Privacy Policy statement explains the data processing practices of datagenf.com. If you have any requests concerning your personal information or any queries with regard to these practices, please send us an e-mail at privacy policy at datagenf.com.</p>
            <p>datagenf.com is steadfast in acknowledging and protecting the privacy and confidentiality of Personal Information of its Employees including prospects, clients, business partners, and other distinguishable persons that it may obtain, utilize, access, process, transfer, or store as part of its business. We recognize your concerns about the security of the personal information provided to us as part of our business.</p>
            <p>We operate and manage the website www.datagenf.com, through which we may collect certain personally identifiable information through telemarketing calls. We are committed to ensuring that we comply with our obligations under the Privacy Act 1988 as well as the Australian Privacy Principles (APPs) whenever we collect personally identifiable information.</p>
            <p>By using our services, you accord to our collection and use of the personal
                information you provide in the manner detailed in our Privacy Policy.
                datagenf.com accepts and adheres to the ACMA rules and legislations and
                Data Protection legislation that include Do Not Call Register Act of2006 (DNCR) that aims
                to protect the privacy of individuals. We want you to know about us, how we are gathering
                the information, how we use it, and how you can update it. datagenf.com reserves th
                e right to append or otherwise modify this Privacy Statement
                at any time, so please re-visit www. datagenf.com occasionally to check for updates.</p>
            <p id="What Information Do We Collect?">We collect information from you when you visit our service, register, subscribe to our newsletter, respond to a survey or fill out a form via Email Address and Mailing Address</p>
            <p id="What Information Do We Collect?">datagenf.com obtained your personal information two ways: (1) directly (for example through a telephone survey, or through their participation in a promotion, survey or alike activities); and (2) indirectly (for example, personal information from our clients to perform services/functions on their behalf, multiple data sources and from third parties), rest assured that we use a variety of security technologies and procedures to help protect your personal information from unauthorized access, use, or disclosure.</p>
            <p id="What Information Do We Collect?">Some questions in our charity calls are specific to our charity partners, and the charities named in the call. By expressing interest and opting-in to their brands or products, you are also agreeing to be contacted by them, by phone, SMS or e-mail. You may need to contact datagenf.com, its charity partners, and the charities named in the call, directly, should you decide to opt-out from further communication from these brands.</p>
            <p id="When do we use customer information from third parties?">The information you volunteer to datagenf.com and the information that datagenf.com holds about you, will be shared and used to appropriately target offers and communication from datagenf.com, its other brands, our clients, and from charitable organizations. Marketing communication may be through email, mailing, telemarketing, SMS/MMS depending on which contact channel information you have volunteered.</p>
            <p id="When do we use customer information from third parties?">Your data may be used for analytical purposes. Your data may also be used in conjunction with data we may have received from other sources in order to personalize and target communication to you better, and we may share information with other companies for the same reason.</p>
            <p id="When do we use customer information from third parties?">Please remember that you can OPT-OUT at any time. Furthermore, you can request suppression of your details from datagenf.com database if you would prefer us not to use your information for any of the above. You can also request to know what personal information datagenf.com holds about you, by requesting and writing to us at datagenf.com.</p>
            <p id="Do we share the information we collect with third parties?">We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whos products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest</p>
            <p id="Do we share the information we collect with third parties?">We may engage trusted third party service providers to perform functions and provide services to us such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our service . We will likely share you personal information and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.</p>
            <p id="Do we share the information we collect with third parties?">We may share protions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. if your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, wheter you have visited the service in a shared location, and type of device used to visit research and reporting for us and our advertisers.
            </p>
            <p id="Do we share the information we collect with third parties?">We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas). to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations
            </p>
            <p id="Could my information be transferred to other countries?">We are incorporated in Philippines. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred fom time to time to our offices or personnel , or to third parties, located throughout the world, and may be viewed and hosted anywhere in the wolrd, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fulles extent allowed by applicable law , by using any of the above you voluntarily consent to the transborder transfer and hosting of such information</p>
            <p id="Is the information collected through our service secure?">We take precautions to protect the security of your information. We have physical, electronic, and manegerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However. neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree
                that intentional misconduct will be the standards used to measure our compliance with that duty.</p>
            <p id="Can i update or correct my information?">
                The rights you have to request updates or corrections to the information we collect depend on your relationship with us. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account Such updates corrections chages and deletions will have no effect on other information that we maintain or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction , change or deletion. To protect your privacy and security we may take reasonable steps (such as request a unique password) to verify your identity before granting you profile acces or making corrections you are responsible for maitaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our syste. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non erasable form that will be difficult or impossible for us to locate. Promptly after receiving your reqeust, all personal information stored in databases we activele use , and other readily searchable media will be updated , corrected , changed or deleted , as appropriate , as soon as and to the extent reasonably and technically practicable if you are an end user and wish to update , delete or receive any information we have about you you may do so by contacting the organization of which you are a customer.
            </p>
            <p id="Personnel"> If you are one of our workers or applicants, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen appllicants. You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction , change or deletion.</p>
            <p id="Sale of Business"> We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that protion of us or any of its Corporate Affiliates to which the Service relates , or in the event that we discontinue our business or file a petition or have filed againts us petition in bankruptcy reorganization or similar proceeding , provided that the third party agrees to adhere to the terms of this privacy policy.</p>
        </div>
        <div class="privacyRight">

            <h3>Table of Contents</h3>
            <ul>
                <li><a href="#What Information Do We Collect?">What Information Do We Collect?</a></li>
                <li><a href="#When do we use customer information from third parties?">When do we use customer information from third parties?</a></li>
                <li><a href="#Could my information be transferred to other countries?">Could my information be transferred to other countries?</a></li>
                <li><a href="#Is the information collected through our service secure?">Is the information collected through our service secure?</a></li>
                <li><a href="#Can i update or correct my information?">Can i update or correct my information?.</a></li>
                <li><a href="#Personnel">Personnel</a></li>
                <li><a href="#Sale of Business">Sale of Business</a></li>

            </ul>
        </div>
    </div>
</div>
<?php include('footerdito.php') ?>
</body>

</html>